version: '3'

services:

  visualisation_engine:
    container_name: ${VIZ_HOSTNAME}
    hostname: ${VIZ_HOSTNAME}
    restart: always
    build:
      context: ".."
      dockerfile: config/Dockerfile
      args:
        SETTINGS: ${SETTINGS}
        PORT: ${PORT}
    ports:
      - ${PORT}:${PORT}
    environment:
      SETTINGS: ${SETTINGS}
      PORT: ${PORT}
      POSTGRESS_USER: ${POSTGRESS_USER}
      POSTGRESS_PASSWORD: ${POSTGRESS_PASSWORD}
      POSTGRESS_HOST: ${POSTGRESS_HOST}
      POSTGRESS_PORT: ${POSTGRESS_PORT}
      POSTGRESS_DB: ${POSTGRESS_DB}
